export const items = [
    {
        id: '01',
        name: 'pick\nles',
        author: 'Omar Faruq Tawsif',
        bg: '#e4cdac',
        width: 1,
        height: 1.618,
        modelSrc:
            'pickles_3d_version_of_hyuna_lees_illustration-transformed.glb',
        modelScale: 8,
        modelPosition: [0, -0.7, -2],
    },
    {
        id: '02',
        name: 'tea',
        author: 'Omar Faruq Tawsif',
        bg: '#f5f5f5',
        width: 1,
        height: 1.618,
        modelSrc: 'fiesta_tea-transformed.glb',
        modelScale: 1,
        modelPosition: [0, -2, -3],
    },
    {
        id: '03',
        name: 'still',
        author: 'Omar Faruq Tawsif',
        bg: '#d1d1ca',
        width: 1,
        height: 1.618,
        modelSrc: 'still_life_based_on_heathers_artwork-transformed.glb',
        modelScale: 2,
        modelPosition: [0, -0.8, -4],
    },
    {
        id: '04',
        name: 'still 2',
        author: 'Omar Faruq Tawsif',
        bg: '#d1d1ca',
        width: 1,
        height: 1.618,
        modelSrc: 'still_life_based_on_heathers_artwork-transformed.glb',
        modelScale: 2,
        modelPosition: [0, -0.8, -4],
    },
    {
        id: '05',
        name: 'still 3',
        author: 'Omar Faruq Tawsif',
        bg: '#d1d1ca',
        width: 1,
        height: 1.618,
        modelSrc: 'still_life_based_on_heathers_artwork-transformed.glb',
        modelScale: 2,
        modelPosition: [0, -0.8, -4],
    },
    {
        id: '06',
        name: 'still 3',
        author: 'Omar Faruq Tawsif',
        bg: '#d1d1ca',
        width: 1,
        height: 1.618,
        modelSrc: 'still_life_based_on_heathers_artwork-transformed.glb',
        modelScale: 2,
        modelPosition: [0, -0.8, -4],
    },
    {
        id: '07',
        name: 'still 3',
        author: 'Omar Faruq Tawsif',
        bg: '#d1d1ca',
        width: 1,
        height: 1.618,
        modelSrc: 'still_life_based_on_heathers_artwork-transformed.glb',
        modelScale: 2,
        modelPosition: [0, -0.8, -4],
    },
];
